name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        jq-package: ["", "jq", "pyjq"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py
    - name: Conditionally install jq-package
      run: |
        if [[ "${{ matrix.jq-package }}" != "" ]]; then
          pip install ${{ matrix.jq-package }}
        fi
    - name: Install dependencies
      run: |
        pip install -e '.[test]'
    - name: Run tests
      run: |
        pytest
    - name: Does cog need to run?
      if: matrix.python-version == '3.11'
      run: |
        cog --check README.md
